---
- name: Github Pull Request Open
  ignore_errors: yes
  slack:
    token: "{{ slack_token }}"
    #color: good
    parse: none
    msg: |
      >*{{ awx_job_template_name }} Closed (`{{ pr_sha7 }}`)*
      <{{ pr_url }}|{{ pr_url }}> <{{ pr_diff_url }}|(diff)>
      sha: `{{ pr_sha }}` `{{ pr_sha7 }}`
      source_repo: `{{ source_repo }}`  source_branch: `{{ source_branch }}`
      pr_base_repo: `{{ pr_base_repo }}`  pr_base_branch: `{{ pr_base_branch }}`
      <{{ awx_controller_url }}/#/jobs/playbook/{{ awx_job_id }}|[ awx job #{{ awx_job_id }} ]>