---
- name: Github Pull Request Open
  ignore_errors: yes
  slack:
    token: "{{ slack_token }}"
    #color: good
    parse: none
    msg: |
      >*{{ awx_job_template_name }} Opened*
      *pr_sha: `{{ pr_sha }}` (`{{ pr_sha7 }}`)*
      *source_repo: `{{ source_repo }}:*
      *source_branch: `{{ source_branch }}`*
      *launch_type:* `{{ awx_job_launch_type }}`
      <{{ awx_controller_url }}/#/jobs/playbook/{{ awx_job_id }}|[ awx job #{{ awx_job_id }} ]>
